version: '3.9'

services:

  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    # restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
# uncomment the following lines to activate admin
  # adminer:
    # image: adminer
    # container_name: pg_adminer
    # restart: always
    # ports:
    #  - 8086:8080
volumes:
  pgdata:
